## HMM

notebook for HMM analysis

In [2]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import t, norm
import statsmodels.api as smapi
import statsmodels as sm
from statsmodels.stats.diagnostic import acorr_ljungbox

project_root = Path.cwd().parent


if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
    

In [3]:
from src import data_loader as dl
from src import preprocessing as pp
from src import garch
from src.markov_model import hmm, forward

# Download S&P 500 data from 2000-01-01 and compute daily log returns.
feature_matrix =np.array([[0.04, 0.11, -0.03], [0.09, 0.07, 0.01], [0.06, 0.09, 0.03]])

hmm = hmm.HiddenMarkovModel(feature_matrix, 3)
print(hmm.init_prob.shape)
print(hmm.means.shape)
print(hmm.transition_matrix.shape)
print(hmm.transition_matrix)
print(hmm.covariances.shape)

raw_data = dl.load_market_data()
market_data = pp.preprocess_market_data(raw_data)

(3,)
(3, 3)
(3, 3)
[[0.9  0.05 0.05]
 [0.05 0.9  0.05]
 [0.05 0.05 0.9 ]]
(3, 3, 3)
Filtered state probabilities:

[[0.9        0.1       ]
 [0.63636364 0.36363636]
 [0.18908629 0.81091371]]

Row sums:
[1. 1. 1.]

Expected approximately:
Day 1: [0.900, 0.100]
Day 2: [0.636, 0.364]
Day 3: [0.189, 0.811]


/Users/gangmember/regime-var-engine/regime-switching-var/src/markov_model/hmm.py:46: RuntimeWarning: Degrees of freedom <= 0 for slice
  covariance = np.cov(state_data, rowvar=False)
/Users/gangmember/regime-var-engine/regime-switching-var/.venv/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:2901: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/Users/gangmember/regime-var-engine/regime-switching-var/.venv/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:2901: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
